repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]  # Adds unsafe fixes to ruff
      - id: ruff-format
