name: Linux_Container_Workflow

on:
    push:
        branches: [ "dev", "main" ]
        tags: [ '*.*.*' ]
    pull_request:
      branches: 
        - dev
      types: [closed]

env:
    AZURE_REPOSITORY: "demo-version"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        
        # Checkout the Repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2  # Ensure you're using v2 for better control over fetch options

        # Fetch all tags from the repository
        - name: 'Fetch all tags'
          run: git fetch --tags
        
        # Check out the source branch of the PR
        - name: 'Checkout pull request branch'
          run: |
            PR_BRANCH="${GITHUB_HEAD_REF}"  # This is the branch from which the PR was created
            git checkout "$PR_BRANCH"

        # Build and push the Docker image
        - run: |
            if [[ $GITHUB_REF == refs/pull/* ]]; then
                # Get the latest tag (associated with the PR source branch)
                TAG_NAME=$(git describe --tags --abbrev=0)  # Get the latest tag from the PR branch
            else
                # It's a tag push, extract the tag name
                TAG_NAME=${GITHUB_REF#refs/tags/}  # Use tag name for push
            echo "Using tag: $TAG_NAME"