name: Linux_Container_Workflow

on:
  push:
    branches:
      - dev
    tags: [ '*.*.*' ]

env:
  AZURE_REPOSITORY: "demo-version"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2  # Ensure you're using v2 for better control over fetch options

      # Build and push the Docker image
      - run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # It's a tag push, extract the tag name
            TAG_NAME=${GITHUB_REF#refs/tags/}  # Use tag name for push
          else
            # It's a push to the dev branch, set tag as 'latest'
            TAG_NAME="latest"
          fi

          echo "Using tag: $TAG_NAME"