name: Lint with Ruff

on:
  push:
    branches:
      - main
      - '**'  # This includes all branches
  pull_request:
    branches:
      - main
      - '**'  # This includes all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: ruff check .
